### PR TITLE
#160127975 Add index.html and style.css.

### PR DESCRIPTION
**Pull request by 66hakeem**
**What does this PR do?**

- Adds the index.html and style.css files.

**Relevant Pivotal Tracker Stories**

- #160127975

### CODE REVIEW

**Comment by mozzy11** [comment]
thats cool ..

**Comment by mulondo** [comment]
that's good

**Comment by joelethan** [comment]
Good job

**Comment by Ivankivu** [comment]
Great work man

**Comment by barema4** [comment]
Nice work

**Comment by Ivankivu** [comment]
Good stuff lad. maintain practice

**Comment by kdaglas** [comment]
cool connection... css getting better for you...

**Comment by barema4** [comment]
good work, keep it up

**Pull request merged**
